language: php
php:
  - '5.5.9'
  - '5.6'
  - '7.0'
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
install:
  - composer create-project laravel/laravel
  - cd ./laravel
before_script:
- mysql -e 'create database c9;'
- php artisan migrate

script: phpunit --configuration phpunit.xml
