language: php
php:
  - '5.5.9'
  - '5.6'
  - '7.0'
  - hhvm
matrix:
    allow_failures:
        - php: hhvm
before_install:
  - composer self-update
  - composer create-project laravel/laravel 
  - cd ./laravel 
  - composer require MeestorHok/Blue dev-master 
  - composer update
  - cp ./vendor/MeestorHok/Blue/tests/config/database.php ./app/config/testing/ 
  - cp ./vendor/MeestorHok/Blue/tests/config/app.php ./app/config/testing/ 
  - export APP_ENV="testing"
  - cd ./vendor/MeestorHok/Blue

script: phpunit --configuration phpunit.xml
